const assert=require('node:assert/strict'),B=require('../app/src/main/assets/engine.js'),{Progress}=require('../app/src/main/assets/progress.js'),{Tutorial}=require('../app/src/main/assets/tutorial.js');
const storage={v:null,getItem(){return this.v},setItem(k,v){this.v=v}},p=new Progress(storage);
assert.equal(p.purchase('longnose_artillery'),false);p.coins=500;assert.equal(p.purchase('longnose_artillery'),true);assert.equal(p.coins,0);assert.equal(p.purchase('longnose_artillery'),false);p.equip('longnose_artillery');assert.equal(new Progress(storage).selected,'longnose_artillery');
assert.equal(p.completeTutorial(),100);assert.equal(p.completeTutorial(),0);assert.equal(new Progress(storage).completeTutorial(),0);
const tick=(e,t)=>{for(let i=0;i<t*120;i++)e.update(1/120);};
let e=new B.Engine({mode:'lan',countdown:0,vehicles:['longnose_artillery','handlv_missile']});
assert.equal(e.players[0].weapons.join(','),'artillery,uav,mg');assert.equal(B.vehicleSpec(e.players[0].vehicleId).recon,250);
for(const k of ['sam','missile'])assert.equal(e.command(0,{type:'select',weapon:k}).ok,false);
Object.assign(e.players[0],{x:1000,z:1600,y:B.terrain(1000,1600)});Object.assign(e.players[1],{x:1000,z:950,y:B.terrain(1000,950)});
assert.equal(e.command(0,{type:'map-aim',x:1000,z:950}).ok,true);const arc=B.ballistic(e.players[0]);assert.ok(B.dist(arc.hit,{x:1000,z:950})<1);
assert.equal(e.command(0,{type:'map-aim',x:0,z:0}).ok,false);
const shot=e.launch(e.players[0],'artillery');Object.assign(shot,{x:e.players[1].x,y:e.players[1].y+3,z:e.players[1].z});e.explode(shot,true);assert.equal(e.players[1].hp,14);
assert.equal(B.TREES.length,800);const tree=B.TREES.find(t=>t.x>100&&t.x<1900&&t.z>100&&t.z<1900);
assert.ok(B.treeHit({x:tree.x-10,y:tree.y+2,z:tree.z},{x:tree.x+10,y:tree.y+2,z:tree.z}));assert.equal(B.clearGround(tree.x,tree.z),false);
const counts={};for(let seed=1;seed<60;seed++){const q=new B.Engine({seed});counts[q.players[1].vehicleId]=true;}assert.equal(Object.keys(counts).length,2);
for(const difficulty of ['easy','standard','hard']){const q=new B.Engine({seed:120,difficulty,vehicles:['handlv_missile','longnose_artillery'],countdown:0});for(let i=0;i<1800;i++){q.update(.05);assert.ok(q.players[1].weapons.includes(q.players[1].selected));assert.ok(q.shots.every(s=>s.owner!==1||s.kind==='bullet'||q.players[1].weapons.includes(s.kind)));}}
e=new B.Engine({mode:'tutorial',countdown:0,vehicles:['handlv_missile','handlv_missile']});const t=new Tutorial(e);assert.equal(t.step,0);t.advance();t.advance();e.players[0].z-=11;t.tick();assert.equal(t.step,3);tick(e,7.1);t.tick();assert.equal(t.step,4);assert.equal(e.players[1].intel.lock,null);assert.ok(e.players[0].intel.clues.length);t.advance();
e.players[0].selected='uav';const u=e.launch(e.players[0],'uav');Object.assign(u,{x:e.players[1].x,z:e.players[1].z+100,y:e.players[1].y+50});e.updateIntel();t.tick();assert.equal(t.step,6);e.startOrbit(u);t.tick();assert.equal(t.step,7);e.players[1].hp-=80;t.tick();assert.equal(t.step,8);assert.ok(e.players[1].intel.lock?.visible);t.advance();assert.equal(t.step,9);
e.players[0].selected='sam';assert.equal(e.command(0,{type:'fire'}).ok,true);for(let i=0;i<1200&&t.step===9;i++){e.update(1/120);t.tick();}assert.equal(t.step,10);
e.players[0].selected='mg';e.players[0].mg=true;for(let i=0;i<600&&t.step===10;i++){e.update(1/120);t.tick();}assert.equal(t.step,11);
e.damage(e.players[1],0,100);t.tick();assert.equal(t.done,true);
console.log('PASS purchase/persistence/one-time tutorial reward, 152mm blast/map targeting, shared trees, random AI pool/mounted weapons, full tutorial SAM/MG physical interceptions');
