const assert=require('node:assert/strict'),fs=require('node:fs'),{open}=require('./browser-helpers.cjs');
(async()=>{
 const{browser,server,url}=await open(),page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto(url);await page.waitForFunction(()=>GameDebug.renderer.modelsReady);await page.evaluate(()=>{GameDebug.profile.coins=500;GameDebug.profile.save();});
  await page.locator('#openShop').click();await page.locator('#buyLongnose').click();assert.equal(await page.evaluate(()=>GameDebug.profile.coins),0);assert.equal(await page.locator('#buyLongnose').textContent(),'已拥有');await page.locator('#shopClose').click();
  await page.locator('#openWarehouse').click();await page.locator('#vehicle-longnose_artillery').click();for(const t of ['27 m/s','250 m','86 HP','20 m','1000 m','5 秒'])assert.ok((await page.locator('#modalCard').textContent()).includes(t),t);await page.locator('#equipVehicle').click();await page.locator('#vehicleBackTop').click();await page.locator('#warehouseClose').click();
  await page.locator('#startAI').click();await page.evaluate(()=>{const e=GameDebug.engine;e.mode='lan';e.countdown=0;Object.assign(e.players[0],{x:1000,z:1600,y:Blindfire.terrain(1000,1600)});Object.assign(e.players[1],{x:1000,z:950,y:Blindfire.terrain(1000,950)});});await page.waitForFunction(()=>GameDebug.renderer.ownTruck.userData.vehicleId==='longnose_artillery');
  const parts=await page.evaluate(()=>{const g=GameDebug.renderer.ownTruck.userData;return {wheels:g.wheels.length,tracks:!!g.tracks,turret:!!g.turret,barrel:!!g.barrel}});console.log('Bear parts',parts);assert.ok(parts.wheels>=24&&parts.tracks&&parts.turret&&parts.barrel);
  await page.evaluate(()=>GameDebug.select('artillery'));await page.locator('#mapAimToggle').click();await page.waitForFunction(()=>GameDebug.renderer.cameraKey==='mapAim');
  await page.evaluate(()=>GameDebug.dispatch({type:'map-aim',x:1000,z:950}));await page.waitForFunction(()=>GameDebug.renderer.lastArc?.hit&&Blindfire.dist(GameDebug.renderer.lastArc.hit,{x:1000,z:950})<2);
  const out='test-output';fs.mkdirSync(out,{recursive:true});await page.screenshot({path:out+'/bear-map.png'});
  await page.locator('#mapAimToggle').click();await page.evaluate(()=>GameDebug.dispatch({type:'aim',yaw:.4,pitch:1.1}));await page.waitForFunction(()=>Math.abs(GameDebug.renderer.ownTruck.userData.barrel.rotation.x-1.1)<.01);
  const original=await page.evaluate(()=>Array.from(GameDebug.renderer.ownTruck.userData.tracks.mesh.geometry.attributes.position.array).slice(0,12));await page.keyboard.down('w');await page.waitForFunction(()=>GameDebug.view.own.wheelTravel>4);await page.keyboard.up('w');assert.notDeepEqual(await page.evaluate(()=>Array.from(GameDebug.renderer.ownTruck.userData.tracks.mesh.geometry.attributes.position.array).slice(0,12)),original);await page.screenshot({path:out+'/bear-model.png'});
  await page.evaluate(()=>{const e=GameDebug.engine,p=e.players[0],q=e.players[1];q.x=p.x+100;q.z=p.z;q.y=p.y;e.updateIntel();});await page.waitForFunction(()=>document.querySelectorAll('.enemy-dot').length>0);await page.evaluate(()=>GameDebug.dispatch({type:'aim',yaw:-Math.PI/2,pitch:.8}));await page.waitForFunction(()=>document.querySelector('.enemy-dot[data-edge="true"]'));await page.evaluate(()=>GameDebug.returnMenu());
  await page.locator('#openTutorial').click();await page.locator('#tutorialNext').click();await page.locator('#tutorialNext').click();await page.keyboard.down('w');await page.waitForFunction(()=>GameDebug.tutorial.step===3);await page.keyboard.up('w');await page.waitForFunction(()=>GameDebug.tutorial.step===4,{timeout:20000});assert.equal(await page.evaluate(()=>GameDebug.engine.players[1].intel.lock),null);await page.screenshot({path:out+'/tutorial-clue.png'});await page.locator('#tutorialNext').click();
  await page.locator('#fireButton').click();await page.waitForFunction(()=>GameDebug.tutorial.step===6,{timeout:25000});await page.locator('#uavOrbit').click();await page.waitForFunction(()=>GameDebug.tutorial.step===7);assert.equal(await page.evaluate(()=>GameDebug.view.own.vehicleId),'handlv_missile');
  // Verify real launcher geometry is articulated, rather than the hidden fallback.
  const launcher=await page.evaluate(()=>GameDebug.renderer.ownTruck.userData.launcher?.children[0].geometry.index.count);console.log('Avenger launcher indices',launcher);assert.ok(launcher>0);
  await page.evaluate(()=>GameDebug.dispatch({type:'aim',yaw:.6,pitch:.2}));await page.waitForTimeout(200);assert.ok(await page.evaluate(()=>Math.abs(GameDebug.renderer.ownTruck.userData.launcher.rotation.z+.6)<.01));
  // Complete the remaining lesson through the same aim/fire inputs, without moving targets or changing HP.
  await page.evaluate(()=>{window.lessonTarget={...GameDebug.view.enemy};GameDebug.dispatch({type:'aim',yaw:0,pitch:.08});});
  await page.locator('#fireButton').click();
  const guidePilot=()=>page.evaluate(()=>{window.guidance=setInterval(()=>{const s=GameDebug.view.shots.find(s=>s.mine&&s.id===GameDebug.view.own.pilot),q=window.lessonTarget;if(!s||!q){clearInterval(window.guidance);return;}const d=Blindfire.dist(s,q);GameDebug.dispatch({type:'aim',yaw:Math.atan2(q.x-s.x,s.z-q.z),pitch:Math.atan2(q.y+3-s.y,Math.max(1,d))});},40);});
  await guidePilot();await page.waitForFunction(()=>GameDebug.tutorial.step===8,{timeout:20000});await page.locator('#tutorialNext').click();await page.locator('[data-weapon="sam"]').click();await page.locator('#fireButton').click();await page.waitForFunction(()=>GameDebug.tutorial.step===10,{timeout:15000});
  await page.locator('[data-weapon="mg"]').click();await page.keyboard.down(' ');await page.waitForFunction(()=>GameDebug.tutorial.step===11,{timeout:10000});await page.keyboard.up(' ');
  await page.locator('#uavOrbit').click();await guidePilot();await page.waitForSelector('#roundCoins',{timeout:20000});assert.equal(await page.evaluate(()=>GameDebug.profile.coins),100);assert.equal(await page.evaluate(()=>GameDebug.profile.tutorialDone),true);
  await page.locator('#backMenu').click();await page.reload();await page.waitForFunction(()=>GameDebug.renderer.modelsReady);assert.equal(await page.evaluate(()=>GameDebug.profile.coins),100);assert.equal(await page.evaluate(()=>GameDebug.profile.completeTutorial()),0);
  // Production first launch forces welcome; completion removes the first-launch gate.
  const prod=await browser.newPage({viewport:{width:390,height:844}});await prod.goto(url.replace('?test=1',''));await prod.waitForSelector('#tutorialNext');assert.equal(await prod.locator('#tutorialTitle').textContent(),'欢迎来到盲区交火');await prod.close();
  assert.deepEqual(errors,[]);console.log('PASS shop/garage, textured bear articulation/tracks/map, enemy red dots, real tutorial movement/flyby/scout/orbit, launcher yaw and production first-launch tutorial');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1)});
