const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{open}=require('./browser-helpers.cjs');
(async()=>{
 const{browser,server,url}=await open(),context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto(url);await page.waitForFunction(()=>window.GameDebug?.renderer.modelsReady);await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('#coinBalance').textContent(),'0');await page.locator('#openShop').click();assert.ok((await page.locator('#modalCard').textContent()).includes('500战币'));await page.locator('#shopClose').click();
  await page.locator('#openWarehouse').click();await page.locator('#vehicle-handlv_missile').click();assert.equal(await page.locator('#modalCard h3').textContent(),'悍驴导弹车');assert.equal(await page.locator('.weapon-spec').count(),4);assert.equal(await page.locator('[data-spec="artillery"]').count(),0);
  const info=await page.locator('#modalCard').textContent();for(const text of['100 HP','33 m/s','300 m','400 m','200 m','25 秒','22 秒','10 秒','无冷却'])assert.ok(info.includes(text),text);
  await page.locator('#vehicleBack').click();await page.locator('#warehouseClose').click();
  for(const[width,height]of[[320,568],[360,640],[412,915],[768,1024]]){await page.setViewportSize({width,height});const layout=await page.evaluate(()=>{const ids=['openShop','openWarehouse','startAI','openLAN'];return {overflow:document.body.scrollWidth>innerWidth,buttons:ids.map(id=>{const r=document.getElementById(id).getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),brand:document.querySelector('.brand').getBoundingClientRect().bottom,difficulty:document.querySelector('.difficulty').getBoundingClientRect().top};});assert.equal(layout.overflow,false);assert.ok(layout.buttons.every(Boolean));assert.ok(layout.brand<=layout.difficulty+1);}
  await page.setViewportSize({width:390,height:844});await page.locator('#startAI').click();await page.evaluate(()=>{const e=GameDebug.engine,B=Blindfire;e.mode='lan';e.countdown=0;Object.assign(e.players[0],{x:1000,z:1000,y:B.terrain(1000,1000),yaw:0});});await page.waitForFunction(()=>GameDebug.view.started);
  assert.equal(await page.locator('.weapon:not(.hidden)').count(),4);assert.equal(await page.locator('[data-weapon="artillery"]').isVisible(),false);
  assert.equal(await page.evaluate(()=>GameDebug.engine.command(0,{type:'select',weapon:'artillery'}).ok),false);await page.keyboard.press('3');await page.waitForFunction(()=>GameDebug.view.own.selected==='sam');await page.keyboard.press('4');await page.waitForFunction(()=>GameDebug.view.own.selected==='mg');
  const wheels=await page.evaluate(()=>GameDebug.renderer.ownTruck.userData.wheels.map(w=>({radius:w.radius,triangles:w.triangles,angle:w.pivot.rotation.y,material:w.pivot.children[0].material===GameDebug.renderer.ownTruck.getObjectByName('mesh_331_mat_70_0').material})));assert.equal(wheels.length,4);assert.ok(wheels.every(w=>w.radius>.4&&w.radius<.6&&w.triangles>200&&w.material));
  await page.keyboard.down('w');await page.waitForFunction(()=>GameDebug.view.own.wheelTravel>4);await page.keyboard.up('w');const rolling=await page.evaluate(()=>GameDebug.renderer.ownTruck.userData.wheels[0].pivot.rotation.y);assert.notEqual(rolling,wheels[0].angle);
  await page.locator('#pauseButton').click();const frozen=await page.evaluate(()=>GameDebug.renderer.ownTruck.userData.wheels[0].pivot.rotation.y);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>GameDebug.renderer.ownTruck.userData.wheels[0].pivot.rotation.y),frozen);await page.locator('#resume').click();
  await page.evaluate(()=>GameDebug.engine.finish(0,'验证胜利'));await page.waitForSelector('#roundCoins');assert.ok((await page.locator('#roundCoins').textContent()).includes('+100'));await page.evaluate(()=>{for(let i=0;i<20;i++)GameDebug.updateHUD();});assert.equal(await page.evaluate(()=>GameDebug.profile.coins),100);await page.locator('#backMenu').click();
  await page.locator('#startAI').click();await page.evaluate(()=>GameDebug.engine.finish(1,'验证失败'));await page.waitForSelector('#roundCoins');await page.locator('#backMenu').click();assert.equal(await page.locator('#coinBalance').textContent(),'125');
  await page.locator('#startAI').click();await page.evaluate(()=>GameDebug.returnMenu());assert.equal(await page.locator('#coinBalance').textContent(),'125');await page.reload();await page.waitForFunction(()=>window.GameDebug?.renderer.modelsReady);assert.equal(await page.locator('#coinBalance').textContent(),'125');
  const output=process.env.TEST_OUTPUT||'test-output';fs.mkdirSync(output,{recursive:true});await page.screenshot({path:path.resolve(output,'garage-menu.png')});await page.locator('#openWarehouse').click();await page.locator('#vehicle-handlv_missile').click();await page.screenshot({path:path.resolve(output,'garage-specs.png')});
  assert.deepEqual(errors,[]);console.log('PASS real WebGL / four textured wheels / portrait menu / shop and full vehicle stats / mounted weapon UI / shortcuts / pause / result rewards and persistence');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1)});
