const assert=require('node:assert/strict');const{open}=require('./browser-helpers.cjs');
(async()=>{
 const{browser,server,url}=await open();const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const a=await context.newPage(),b=await context.newPage(),errors=[];let host=null,guest=null,linked=false,frames=0,maxBytes=0;
 try{
  for(const p of[a,b]){
   p.on('pageerror',e=>errors.push(e.message));await p.exposeBinding('bridgeCall',async(source,kind,data)=>{
    if(kind==='host'){host=source.page;await host.evaluate(()=>onNativeNetwork({type:'listening',code:'123456',ips:['127.0.0.1']}));}
    else if(kind==='join'){assert.equal(data.ip,'127.0.0.1');assert.equal(data.code,'123456');guest=source.page;linked=true;await guest.evaluate(()=>onNativeNetwork({type:'connected',role:'guest'}));await host.evaluate(()=>onNativeNetwork({type:'connected',role:'host'}));}
    else if(kind==='send'&&linked){const packet=JSON.parse(data),other=source.page===host?guest:host;if(packet.type==='state'){frames++;maxBytes=Math.max(maxBytes,Buffer.byteLength(data));assert.ok(data.length<65536);for(const s of packet.view.shots.filter(s=>!s.mine))assert.equal('owner' in s,false);}await other.evaluate(d=>onNativeNetwork({type:'data',data:d}),data);}
    else if(kind==='leave'&&linked){linked=false;const other=source.page===host?guest:host;await other.evaluate(()=>onNativeNetwork({type:'closed',message:'对方已断开连接。'}));}
   });await p.addInitScript(()=>{window.Native={host:()=>bridgeCall('host'),join:(ip,code)=>bridgeCall('join',{ip,code}),send:data=>bridgeCall('send',data),leave:()=>bridgeCall('leave'),vibrate:()=>{},finishApp:()=>{}};});await p.goto(url);await p.waitForFunction(()=>window.GameDebug&&GameDebug.renderer.ready&&GameDebug.renderer.modelsReady);
  }
  await a.locator('#openLAN').click();await a.locator('#hostRoom').click();await a.waitForSelector('.room-code');assert.equal(await a.locator('.room-code').textContent(),'123456');await b.locator('#openLAN').click();await b.locator('#joinRoom').click();await b.locator('#hostIP').fill('127.0.0.1');await b.locator('#hostCode').fill('123456');await b.locator('#connectRoom').click();await a.waitForFunction(()=>GameDebug.view&&GameDebug.view.started);await b.waitForFunction(()=>GameDebug.view&&GameDebug.view.started);
  for(const p of[a,b]){assert.equal(await p.evaluate(()=>GameDebug.view.enemy),null);assert.equal(await p.evaluate(()=>GameDebug.view.own.hp),100);assert.equal(await p.evaluate(()=>GameDebug.renderer.cameraKey),'truck');}assert.ok((await b.locator('#modeLabel').textContent()).includes('玩家 B'));
  // Exercise continuous guest input through the host, with no guest simulation.
  const old=await a.evaluate(()=>GameDebug.engine.players[1].z);await b.keyboard.down('w');await b.waitForFunction(()=>GameDebug.view.own.speed>3);await b.keyboard.up('w');await b.waitForFunction(()=>GameDebug.view.own.speed<1);assert.notEqual(await a.evaluate(()=>GameDebug.engine.players[1].z),old);
  await b.locator('[data-weapon="mg"]').click();const f=await b.locator('#fireButton').boundingBox();await b.mouse.move(f.x+f.width/2,f.y+f.height/2);await b.mouse.down();await a.waitForFunction(()=>GameDebug.engine.players[1].mg);await b.mouse.up();await a.waitForFunction(()=>!GameDebug.engine.players[1].mg);
  await a.evaluate(()=>{const e=GameDebug.engine,p=e.players[1];e.command(0,{type:'vehicle'});e.command(0,{type:'select',weapon:'uav'});const r=e.command(0,{type:'fire'}),q=e.shots.find(s=>s.id===r.id);Object.assign(q,{x:p.x+50,y:p.y+75,z:p.z+(p.z>400?-180:180),speed:30,pitch:0});});await b.locator('[data-weapon="sam"]').click();await b.evaluate(()=>GameDebug.dispatch({type:'aim',yaw:1,pitch:.6},true));await b.locator('#fireButton').click();await b.waitForFunction(()=>GameDebug.view.own.cd.sam>20&&GameDebug.view.own.pilot===null&&GameDebug.renderer.cameraKey==='truck');await a.waitForFunction(()=>GameDebug.engine.players[1].stats.intercepted>0);
  // New controls must travel to the authority and appear in both clients' snapshots.
  await a.evaluate(()=>{const p=GameDebug.engine.players[1];if(!p.weapons.includes('artillery'))p.weapons.push('artillery');});await b.waitForFunction(()=>GameDebug.view.own.weapons.includes('artillery'));await b.locator('[data-weapon="artillery"]').click();await b.locator('#artilleryMode').click();await a.waitForFunction(()=>GameDebug.engine.players[1].artilleryMode==='direct');await b.waitForFunction(()=>GameDebug.view.own.artilleryMode==='direct');
  await b.locator('#fireButton').click();await a.waitForFunction(()=>GameDebug.engine.shots.some(s=>s.owner===1&&s.kind==='artillery'&&s.artilleryMode==='direct'));await b.waitForFunction(()=>GameDebug.audio.stats.events.artillery===1);
  await b.locator('#artilleryMode').click();await a.waitForFunction(()=>GameDebug.engine.players[1].artilleryMode==='curve');assert.ok(await b.evaluate(()=>GameDebug.view.own.cd.artillery>0));
  await b.locator('[data-weapon="uav"]').click();await b.locator('#fireButton').click();await b.waitForFunction(()=>GameDebug.view.own.pilot!==null);await b.locator('#uavOrbit').click();await a.waitForFunction(()=>GameDebug.engine.shots.some(s=>s.owner===1&&s.kind==='uav'&&s.orbit));await b.waitForFunction(()=>GameDebug.view.own.pilot===null&&GameDebug.view.shots.some(s=>s.mine&&s.kind==='uav'&&s.orbit));await b.locator('#uavOrbit').click();await a.waitForFunction(()=>GameDebug.engine.players[1].pilot!==null&&GameDebug.engine.shots.some(s=>s.owner===1&&s.kind==='uav'&&!s.orbit));await b.locator('#returnVehicle').click();
  // Use a clear terrain lane so the test checks manual aim and replication,
  // rather than relying on a random round's buildings or a homing missile.
  await a.evaluate(()=>{const e=GameDebug.engine,B=Blindfire;for(const[p,x,z]of[[e.players[0],400,680],[e.players[1],400,1010]]){Object.assign(p,{x,z,y:B.terrain(x,z),speed:0});p.drive={throttle:0,steer:0};}e.shots=[];e.removeDead();});await b.waitForFunction(()=>Math.abs(GameDebug.view.own.z-1010)<.1);
  const aim=await a.evaluate(()=>{const[a,b]=GameDebug.engine.players;return{yaw:Math.atan2(a.x-b.x,b.z-a.z),pitch:Math.atan2(a.y+3-(b.y+5.7),Blindfire.dist(a,b))};});await b.locator('[data-weapon="missile"]').click();await b.evaluate(aim=>GameDebug.dispatch({type:'aim',...aim},true),aim);await b.locator('#fireButton').click();await b.waitForFunction(()=>GameDebug.view.own.cd.missile>0&&GameDebug.view.own.pilot!==null);await b.waitForFunction(()=>GameDebug.renderer.cameraKey.startsWith('flight'));await a.waitForFunction(()=>GameDebug.view.own.hp===20,null,{timeout:10000});await b.waitForFunction(()=>GameDebug.view.own.stats.damage===80);assert.ok(await a.evaluate(()=>GameDebug.view.clues.some(c=>c.kind==='direction')));assert.ok(await b.evaluate(()=>GameDebug.view.enemy&&GameDebug.view.enemy.precise));await a.evaluate(()=>{for(let i=0;i<630;i++)GameDebug.engine.update(1/120);});await b.waitForFunction(()=>GameDebug.view.enemy===null&&!GameDebug.renderer.enemyTruck.visible);assert.ok(frames>40);assert.ok(maxBytes<65536);
  await b.evaluate(()=>GameDebug.returnMenu());await a.waitForSelector('#interruptedBack');assert.ok((await a.locator('#modalCard h3').textContent()).includes('中断'));assert.deepEqual(errors,[]);console.log('PASS two 3D clients: room, hidden intel, guest driving/MG/automatic SAM/manual missile, artillery modes, UAV orbit, confirmed audio, cruise reconnaissance, 5-second intel expiry, cooldown/damage synchronization and disconnect; max snapshot',maxBytes,'bytes');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1)});
